const raiz = "../assets/images/funkos/";

const Lista: Funko[] = [
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 6,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 6,
    estado: "preventa",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 1,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 1,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 6,
    estado: "preventa",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 1,
    estado: "preventa",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 1,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 5,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 6,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 3,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 4,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 1,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 6,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 4,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 6,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 1,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 6,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 1,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 1,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 5,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 6,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 3,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 4,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 1,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 6,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 7,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 6,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 1,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 6,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 1,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 1,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 5,
    estado: "disponible",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 3,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 9,
    estado: "disponible",
  },
  {
    nombre: "Piterman2424",
    ruta: raiz + "piterman/piterman.png",
    precio: 150,
    piezas: 4,
    estado: "preventa",
  },
  {
    nombre: "Nezuko",
    ruta: raiz + "NezukoKamado/Nezuko.png",
    precio: 150,
    piezas: 0,
    estado: "agotado",
  },
];

export default Lista;
