const raiz = "../assets/images/funkos/";

const Lista: Funko[] = [
  {
    nombre: "Bob Burlon #1672",
    serie: "Bob Esponja",
    ruta: raiz + "bobEsponja/bobBurlon1672.png",
    precio: 350,
    piezas: 6,
    estado: "venta",
  },
  {
    nombre: "Bob Cavernicola #1669",
    serie: "Bob Esponja",
    ruta: raiz + "bobEsponja/bobCavernicola1669.png",
    precio: 300,
    piezas: 3,
    estado: "venta",
  },
  {
    nombre: "Bob Guitarra #1666",
    serie: "Bob Esponja",
    ruta: raiz + "bobEsponja/bobGuitarra1666.png",
    precio: 300,
    piezas: 3,
    estado: "venta",
  },
  {
    nombre: "Bob Mundo Guante #1671",
    serie: "Bob Esponja",
    ruta: raiz + "bobEsponja/mundoGuante1671.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Denji #1678",
    serie: "Chainsawman",
    ruta: raiz + "chainsawman/denji1678.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Power #1681",
    serie: "Chainsawman",
    ruta: raiz + "chainsawman/power1681.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Chainsawman #1677",
    serie: "Chainsawman",
    ruta: raiz + "chainsawman/chainsawman1677.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Chainsawman chase #1677",
    serie: "Chainsawman",
    ruta: raiz + "chainsawman/chainsawChase1677.png",
    precio: 550,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Pochita #1682",
    serie: "Chainsawman",
    ruta: raiz + "chainsawman/pochita1682.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Tengen #1533",
    serie: "DemonSlayer",
    ruta: raiz + "demonSlayer/tengen1533.png",
    precio: 300,
    piezas: 5,
    estado: "venta",
  },
  {
    nombre: "Tengen Chase #1533",
    serie: "DemonSlayer",
    ruta: raiz + "demonSlayer/tengenChase1533.png",
    precio: 500,
    piezas: 0,
    estado: "venta",
  },
  {
    nombre: "Tanjuro #1255",
    serie: "DemonSlayer",
    ruta: raiz + "demonSlayer/tanjuro1255.png",
    precio: 150,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Enmu #1158",
    serie: "DemonSlayer",
    ruta: raiz + "demonSlayer/enmu1158.png",
    precio: 400,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Tengen vs Gyutaro #1753",
    serie: "DemonSlayer",
    ruta: raiz + "demonSlayer/tengenvsGyutaro1753.png",
    precio: 750,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Luffy Gear Five #1607",
    serie: "One Piece",
    ruta: raiz + "onePiece/luffyGF1607.png",
    precio: 250,
    piezas: 3,
    estado: "venta",
  },
  {
    nombre: "Monkey D. Luffy #1771",
    serie: "One Piece",
    ruta: raiz + "onePiece/luffy1771.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Nami #1772",
    serie: "One Piece",
    ruta: raiz + "onePiece/nami1772.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Roronoa Zoro #1775",
    serie: "One Piece",
    ruta: raiz + "onePiece/zoro1775.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Sanji #1773",
    serie: "One Piece",
    ruta: raiz + "onePiece/sanji1773.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Usopp #1774",
    serie: "One Piece",
    ruta: raiz + "onePiece/usopp1774.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Borsalino #1786",
    serie: "One Piece",
    ruta: raiz + "onePiece/borsalino1786.png",
    precio: 350,
    piezas: 5,
    estado: "venta",
  },
  {
    nombre: "Corazon #1709",
    serie: "One Piece",
    ruta: raiz + "onePiece/corazon1709.png",
    precio: 550,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Buggy the Clown #1276",
    serie: "One Piece",
    ruta: raiz + "onePiece/buggy1276.png",
    precio: 380,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Luffi & Foxy #2",
    serie: "One Piece",
    ruta: raiz + "onePiece/luffi&foxy2.png",
    precio: 650,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Portgas. D. Ace #100",
    serie: "One Piece",
    ruta: raiz + "onePiece/ace100.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Orobi #1475",
    serie: "One Piece",
    ruta: raiz + "onePiece/orobi1475.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Armored Chopper #1131",
    serie: "One Piece",
    ruta: raiz + "onePiece/chopperArmored1131.png",
    precio: 330,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Red Hawk Luffy #1273",
    serie: "One Piece",
    ruta: raiz + "onePiece/luffyRedHawk1273.png",
    precio: 330,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Gol D. Roger #1274",
    serie: "One Piece",
    ruta: raiz + "onePiece/golDRoger1274.png",
    precio: 350,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Monkey. D. Luffy #98",
    serie: "One Piece",
    ruta: raiz + "onePiece/luffyNormal98.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Luffy #1620",
    serie: "One Piece",
    ruta: raiz + "onePiece/luffy1620.png",
    precio: 330,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Yamato #1596",
    serie: "One Piece",
    ruta: raiz + "onePiece/yamato1596.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Yuji Itadori #1645",
    serie: "Jujutsu Kaisen",
    ruta: raiz + "jujutsuKaisen/itadori1645.png",
    precio: 350,
    piezas: 3,
    estado: "venta",
  },
  {
    nombre: "Momo Nishimiya #1641",
    serie: "Jujutsu Kaisen",
    ruta: raiz + "jujutsuKaisen/momo1641.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Spider-Punk #1411",
    serie: "Spider-man",
    ruta: raiz + "spiderman/spider-punk1411.png",
    precio: 280,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Spider-Man 2099 #1409",
    serie: "Spider-man",
    ruta: raiz + "spiderman/spider-man20991409.png",
    precio: 280,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Mayday Parker #1410",
    serie: "Spider-man",
    ruta: raiz + "spiderman/maydayParker1410.png",
    precio: 280,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Spider-Man #1441",
    serie: "Spider-man",
    ruta: raiz + "spiderman/spider-man1441.png",
    precio: 300,
    piezas: 3,
    estado: "venta",
  },
  {
    nombre: "Spider-Man #1357",
    serie: "Spider-man",
    ruta: raiz + "spiderman/spider-man1357.png",
    precio: 400,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Spider-Girl #955",
    serie: "Spider-man",
    ruta: raiz + "spiderman/spider-girl955.png",
    precio: 250,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Spider-Man(Capitan Universe) #614",
    serie: "Spider-man",
    ruta: raiz + "spiderman/spider-man614.png",
    precio: 330,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Spider-Man #1136",
    serie: "Spider-man",
    ruta: raiz + "spiderman/spider-man1136.png",
    precio: 350,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Dinopool #777",
    serie: "Dead Pool",
    ruta: raiz + "deadpool/dinopool777.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Deadpool with Headpool #1400",
    serie: "Dead Pool",
    ruta: raiz + "deadpool/headpool1400.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Ladypool #1404",
    serie: "Dead Pool",
    ruta: raiz + "deadpool/ladypool1404.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Grogu #746",
    serie: "Star Wars",
    ruta: raiz + "starWars/grogu746.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Darth Vader #727",
    serie: "Star Wars",
    ruta: raiz + "starWars/darthVader727.png",
    precio: 650,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Stitch with Lights #1504",
    serie: "Disney",
    ruta: raiz + "disney/stitch1504.png",
    precio: 650,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Santa Jack #1383",
    serie: "Disney",
    ruta: raiz + "disney/santaJack1383.png",
    precio: 350,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Sally #16",
    serie: "Disney",
    ruta: raiz + "disney/sally16.png",
    precio: 330,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Wasabi No-Ginger #110",
    serie: "Disney",
    ruta: raiz + "disney/wasabi110.png",
    precio: 450,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Hiro Hamada #109",
    serie: "Disney",
    ruta: raiz + "disney/hiro109.png",
    precio: 450,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Go Go Tomago #107",
    serie: "Disney",
    ruta: raiz + "disney/gogo107.png",
    precio: 450,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Jack Skellington in snowmobile #104",
    serie: "Disney",
    ruta: raiz + "disney/trineoJack104.png",
    precio: 650,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "RM #367",
    serie: "BTS",
    ruta: raiz + "bts/rm367.png",
    precio: 150,
    piezas: 3,
    estado: "venta",
  },
  {
    nombre: "JIN #280",
    serie: "BTS",
    ruta: raiz + "bts/jin280.png",
    precio: 150,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Gill-Man #1632",
    serie: "Universal Monsters",
    ruta: raiz + "universalMonsters/gillman1632.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Frankenstein #1630",
    serie: "Universal Monsters",
    ruta: raiz + "universalMonsters/frankenstein1630.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Bride of Frankenstein #1631",
    serie: "Universal Monsters",
    ruta: raiz + "universalMonsters/brideFrankenstein1631.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Dracula #1634",
    serie: "Universal Monsters",
    ruta: raiz + "universalMonsters/dracula1634.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Patchwork the Joker #511",
    serie: "DC",
    ruta: raiz + "dc/jokerHilo511.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Patchwork Batman #508",
    serie: "DC",
    ruta: raiz + "dc/batmanHilo508.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "The Joker #517",
    serie: "DC",
    ruta: raiz + "dc/theJoker517.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Batman #01",
    serie: "DC",
    ruta: raiz + "dc/batman01.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Batman #458",
    serie: "DC",
    ruta: raiz + "dc/batman458.png",
    precio: 350,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Batgirl(Cassandra Cain) #501",
    serie: "DC",
    ruta: raiz + "dc/batgirl501.png",
    precio: 250,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Todoroki #372",
    serie: "My Hero Academia",
    ruta: raiz + "myHeroAcademia/todoroki372.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Dabi #1522",
    serie: "My Hero Academia",
    ruta: raiz + "myHeroAcademia/dabi1522.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Tenya Iida #1349",
    serie: "My Hero Academia",
    ruta: raiz + "myHeroAcademia/tenya1349.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Spinner #1201",
    serie: "My Hero Academia",
    ruta: raiz + "myHeroAcademia/spinner1201.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Orochimaru(Akatsuki) #1435",
    serie: "Naruto",
    ruta: raiz + "naruto/orochimaru1435.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Pochacco #1021",
    serie: "Naruto",
    ruta: raiz + "naruto/pochacco1021.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Pain vs Naruto #1433",
    serie: "Naruto",
    ruta: raiz + "naruto/painvsNaruto1433.png",
    precio: 750,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Ansiedad #1447",
    serie: "Intensamente",
    ruta: raiz + "intensamente/ansiedad1447.png",
    precio: 400,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Envy on memory Orb #1449",
    serie: "Intensamente",
    ruta: raiz + "intensamente/envy1449.png",
    precio: 350,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Dragon Shiryu #807",
    serie: "Caballeros del Zodiaco",
    ruta: raiz + "caballerosdelZodiaco/shiryu807.png",
    precio: 250,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Aquarius Hyoga #1425",
    serie: "Caballeros del Zodiaco",
    ruta: raiz + "caballerosdelZodiaco/hyoga1425.png",
    precio: 250,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Phoenix Ikki #810",
    serie: "Caballeros del Zodiaco",
    ruta: raiz + "caballerosdelZodiaco/ikki810.png",
    precio: 250,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Leo Ikki #1427",
    serie: "Caballeros del Zodiaco",
    ruta: raiz + "caballerosdelZodiaco/leoIkki1427.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Hello Kitty #89",
    serie: "Hello Kitty",
    ruta: raiz + "kitty/helloKitty89.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Kuromi #90",
    serie: "Hello Kitty",
    ruta: raiz + "kitty/kuromi90.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Axl Rose #397",
    serie: "Guns and Roses",
    ruta: raiz + "gunsNRoses/axlRose397.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "slash #398",
    serie: "Guns and Roses",
    ruta: raiz + "gunsNRoses/slash398.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Goku Ultra Instinto #1232",
    serie: "Dragon Ball",
    ruta: raiz + "dragonBall/gokuUI1232.png",
    precio: 350,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Super Saiyan 3 Goku #1633",
    serie: "Dragon Ball",
    ruta: raiz + "dragonBall/sS3Goku1633.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Odin #54",
    serie: "Marvel",
    ruta: raiz + "marvel/odin54.png",
    precio: 150,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Ban #1341",
    serie: "los 7 Pecados Capitales, los siete Pecados Capitales",
    ruta: raiz + "los7PecadosCapitales/ban1341.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Chimchar Flocked #963",
    serie: "Pokemon, Pokémon",
    ruta: raiz + "pokemon/chimcharFlocked963.png",
    precio: 350,
    piezas: 5,
    estado: "venta",
  },
  {
    nombre: "Sprigatito #984",
    serie: "Pokemon, Pokémon",
    ruta: raiz + "pokemon/sprigatito984.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Lucario #856",
    serie: "Pokemon, Pokémon",
    ruta: raiz + "pokemon/lucario856.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "The Catman #124",
    serie: "Kiss",
    ruta: raiz + "kiss/catman124.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Lord Soth #979",
    serie: "Dungeons & Dragons",
    ruta: raiz + "dungeonsandDragons/lordSothGlow979.png",
    precio: 350,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Kei Tsukishima #1390",
    serie: "Haikyu",
    ruta: raiz + "haikyu/tsukishima1390.png",
    precio: 350,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Mexico #1076",
    serie: "Iconos",
    ruta: raiz + "iconos/mexico1076.png",
    precio: 250,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Finn el humano #1077",
    serie: "Hora de aventura",
    ruta: raiz + "horadeAventura/finntheHuman1077.png",
    precio: 250,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Beetlejuice #1689",
    serie: "Peliculas",
    ruta: raiz + "peliculas/beetlejuice1689.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "El chavo #751",
    serie: "Serie de television",
    ruta: raiz + "seriesTelevisivas/elChavo751.png",
    precio: 800,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Coraline with dowsing Rod #1661",
    serie: "Coraline",
    ruta: raiz + "coraline/coraline1661.png",
    precio: 650,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Ramona Flowers #1715",
    serie: "Scott Pilgrim",
    ruta: raiz + "scottPilgrim/ramonaFlowers1715.png",
    precio: 300,
    piezas: 3,
    estado: "venta",
  },
  {
    nombre: "Rukia Kuchiki #1617",
    serie: "Bleach",
    ruta: raiz + "bleach/rukiaKuchiki1617.png",
    precio: 250,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Hopper #512",
    serie: "Stranger Things",
    ruta: raiz + "strangerThings/hopper512.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Steve(with sunglasses) #638",
    serie: "Stranger Things",
    ruta: raiz + "strangerThings/steve638.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Legolas #628",
    serie: "El señor de los anillos, Lord of the Rings",
    ruta: raiz + "lordRings/legolas628.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Winged Kuriboh #1601",
    serie: "Yu-Gi-Oh, Yu Gi Oh",
    ruta: raiz + "yugioh/kuriboAlado1601.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
];

export default Lista;
