const raiz = "../assets/images/funkos/";

const Lista: Funko[] = [
  {
    nombre: "Denji #1678",
    serie: "Chainsawman, Chainsaw man",
    ruta: raiz + "chainsawman/denji1678.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "AKI HAYAKAWA #1972",
    serie: "Chainsawman, Chainsaw man",
    ruta: raiz + "chainsawman/aki1972.webp",
    precio: 750,
    piezas: 2,
    estado: "Preventa",
  },
  {
    nombre: "Power #1681",
    serie: "Chainsawman, Chainsaw man",
    ruta: raiz + "chainsawman/power1681.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Power #1973",
    serie: "Chainsawman, Chainsaw man",
    ruta: raiz + "chainsawman/power1973.webp",
    precio: 650,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Pochita #1682",
    serie: "Chainsawman, Chainsaw man",
    ruta: raiz + "chainsawman/pochita1682.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Tengen #1533",
    serie: "DemonSlayer",
    ruta: raiz + "demonSlayer/tengen1533.png",
    precio: 300,
    piezas: 5,
    estado: "venta",
  },
  {
    nombre: "Tanjuro #1255",
    serie: "DemonSlayer",
    ruta: raiz + "demonSlayer/tanjuro1255.png",
    precio: 150,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Enmu #1158",
    serie: "DemonSlayer",
    ruta: raiz + "demonSlayer/enmu1158.png",
    precio: 400,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Luffy & Foxy #2",
    serie: "One Piece",
    ruta: raiz + "onePiece/luffy&foxy2.png",
    precio: 650,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Orobi #1475",
    serie: "One Piece",
    ruta: raiz + "onePiece/orobi1475.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Yamato #1596",
    serie: "One Piece",
    ruta: raiz + "onePiece/yamato1596.png",
    precio: 500,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Bartholomew Kuma #1876",
    serie: "One Piece",
    ruta: raiz + "onePiece/kuma1876.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Tony Tony Chopper #1946",
    serie: "One Piece",
    ruta: raiz + "onePiece/chopper1946.jpg",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Godzilla #1890",
    serie: "Godzilla",
    ruta: raiz + "godzilla/godzilla1890.webp",
    precio: 550,
    piezas: 3,
    estado: "venta",
  },
  {
    nombre: "Yuji Itadori #1645",
    serie: "Jujutsu Kaisen",
    ruta: raiz + "jujutsuKaisen/itadori1645.png",
    precio: 350,
    piezas: 3,
    estado: "venta",
  },
  {
    nombre: "Momo Nishimiya #1641",
    serie: "Jujutsu Kaisen",
    ruta: raiz + "jujutsuKaisen/momo1641.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Yuji Itadori #1882",
    serie: "Jujutsu Kaisen",
    ruta: raiz + "jujutsuKaisen/itadori1882.webp",
    precio: 400,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Connie Springer #1991",
    serie: "shingeki no kyojin, SNK, Attack on Titan",
    ruta: raiz + "shingeki/connie1991.webp",
    precio: 300,
    piezas: 2,
    estado: "preventa",
  },
  {
    nombre: "Jean Kirstein #1992",
    serie: "shingeki no kyojin, SNK, Attack on Titan",
    ruta: raiz + "shingeki/jean1992.webp",
    precio: 300,
    piezas: 2,
    estado: "preventa",
  },
  {
    nombre: "LEVI #1993",
    serie: "shingeki no kyojin, SNK, Attack on Titan",
    ruta: raiz + "shingeki/levi1993.webp",
    precio: 300,
    piezas: 2,
    estado: "preventa",
  },
  {
    nombre: "Hange Zoe #1994",
    serie: "shingeki no kyojin, SNK, Attack on Titan",
    ruta: raiz + "shingeki/hange1994.webp",
    precio: 300,
    piezas: 2,
    estado: "Preventa",
  },
  {
    nombre: "Armored Titan #1995",
    serie: "shingeki no kyojin, SNK, Attack on Titan",
    ruta: raiz + "shingeki/acorazado1995.webp",
    precio: 1100,
    piezas: 2,
    estado: "Preventa",
  },
  {
    nombre: "Spider-Punk #1411",
    serie: "Spider-man",
    ruta: raiz + "spiderman/spider-punk1411.png",
    precio: 280,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Spider-Man 2099 #1409",
    serie: "Spider-man",
    ruta: raiz + "spiderman/spider-man20991409.png",
    precio: 280,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Mayday Parker #1410",
    serie: "Spider-man",
    ruta: raiz + "spiderman/maydayParker1410.png",
    precio: 280,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Spider-Man #1441",
    serie: "Spider-man",
    ruta: raiz + "spiderman/spider-man1441.png",
    precio: 300,
    piezas: 3,
    estado: "venta",
  },
  {
    nombre: "Spider-Man #1357",
    serie: "Spider-man",
    ruta: raiz + "spiderman/spider-man1357.png",
    precio: 400,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Spider-Girl #955",
    serie: "Spider-man",
    ruta: raiz + "spiderman/spider-girl955.png",
    precio: 250,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Grogu #746",
    serie: "Star Wars",
    ruta: raiz + "starWars/grogu746.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Stitch and the red one",
    serie: "Disney",
    ruta: raiz + "disney/stitchred.png",
    precio: 160,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Sally #16",
    serie: "Disney",
    ruta: raiz + "disney/sally16.png",
    precio: 330,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Hiro Hamada #109",
    serie: "Disney",
    ruta: raiz + "disney/hiro109.png",
    precio: 450,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Jack Skellington in snowmobile #104",
    serie: "Disney",
    ruta: raiz + "disney/trineoJack104.png",
    precio: 650,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Timmy Turner #1690",
    serie: "los padrinos magicos",
    ruta: raiz + "padrinosMagicos/timmy1690.webp",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Cosmo & Poof #1691",
    serie: "los padrinos magicos",
    ruta: raiz + "padrinosMagicos/cosmopoof1691.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Wanda with da rules #1692",
    serie: "los padrinos magicos",
    ruta: raiz + "padrinosMagicos/wanda1692.webp",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "RM #367",
    serie: "BTS",
    ruta: raiz + "bts/rm367.png",
    precio: 150,
    piezas: 3,
    estado: "venta",
  },
  {
    nombre: "RM #464",
    serie: "BTS",
    ruta: raiz + "bts/rm464.webp",
    precio: 300,
    piezas: 2,
    estado: "Preventa",
  },
  {
    nombre: "JIN #465",
    serie: "BTS",
    ruta: raiz + "bts/jin465.webp",
    precio: 300,
    piezas: 2,
    estado: "Preventa",
  },
  {
    nombre: "Agust D #466",
    serie: "BTS",
    ruta: raiz + "bts/agustd466.webp",
    precio: 300,
    piezas: 2,
    estado: "Preventa",
  },
  {
    nombre: "J-Hope #467",
    serie: "BTS",
    ruta: raiz + "bts/jhope467.webp",
    precio: 300,
    piezas: 2,
    estado: "Preventa",
  },
  {
    nombre: "Jimin #468",
    serie: "BTS",
    ruta: raiz + "bts/jimin468.webp",
    precio: 300,
    piezas: 2,
    estado: "Preventa",
  },
  {
    nombre: "V #469",
    serie: "BTS",
    ruta: raiz + "bts/v469.webp",
    precio: 300,
    piezas: 2,
    estado: "Preventa",
  },
  {
    nombre: "Jung Kook #470",
    serie: "BTS",
    ruta: raiz + "bts/jungkook470.webp",
    precio: 300,
    piezas: 2,
    estado: "Preventa",
  },
  {
    nombre: "Gill-Man #1632",
    serie: "Universal Monsters",
    ruta: raiz + "universalMonsters/gillman1632.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Frankenstein #1630",
    serie: "Universal Monsters",
    ruta: raiz + "universalMonsters/frankenstein1630.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Bride of Frankenstein #1631",
    serie: "Universal Monsters",
    ruta: raiz + "universalMonsters/brideFrankenstein1631.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Dracula #1634",
    serie: "Universal Monsters",
    ruta: raiz + "universalMonsters/dracula1634.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Patchwork the Joker #511",
    serie: "DC",
    ruta: raiz + "dc/jokerHilo511.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Patchwork Batman #508",
    serie: "DC",
    ruta: raiz + "dc/batmanHilo508.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "The Joker #517",
    serie: "DC",
    ruta: raiz + "dc/theJoker517.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Batman #01",
    serie: "DC",
    ruta: raiz + "dc/batman01.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Batgirl(Cassandra Cain) #501",
    serie: "DC",
    ruta: raiz + "dc/batgirl501.png",
    precio: 250,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Tenya Iida #1349",
    serie: "My Hero Academia",
    ruta: raiz + "myHeroAcademia/tenya1349.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Spinner #1201",
    serie: "My Hero Academia",
    ruta: raiz + "myHeroAcademia/spinner1201.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Envy on memory Orb #1449",
    serie: "Intensamente",
    ruta: raiz + "intensamente/envy1449.png",
    precio: 350,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Axl Rose #397",
    serie: "Guns and Roses",
    ruta: raiz + "gunsNRoses/axlRose397.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "slash #398",
    serie: "Guns and Roses",
    ruta: raiz + "gunsNRoses/slash398.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Goku Ultra Instinto #1232",
    serie: "Dragon Ball",
    ruta: raiz + "dragonBall/gokuUI1232.png",
    precio: 350,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Super Saiyan 3 Goku #1633",
    serie: "Dragon Ball",
    ruta: raiz + "dragonBall/sS3Goku1633.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Odin #54",
    serie: "Marvel",
    ruta: raiz + "marvel/odin54.png",
    precio: 150,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Sprigatito #984",
    serie: "Pokemon, Pokémon",
    ruta: raiz + "pokemon/sprigatito984.png",
    precio: 300,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Lucario #856",
    serie: "Pokemon, Pokémon",
    ruta: raiz + "pokemon/lucario856.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Kei Tsukishima #1390",
    serie: "Haikyu",
    ruta: raiz + "haikyu/tsukishima1390.png",
    precio: 350,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Beetlejuice #1689",
    serie: "Peliculas",
    ruta: raiz + "peliculas/beetlejuice1689.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "El chavo #751",
    serie: "Serie de television",
    ruta: raiz + "seriesTelevisivas/elChavo751.png",
    precio: 800,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Coraline with dowsing Rod #1661",
    serie: "Coraline",
    ruta: raiz + "coraline/coraline1661.png",
    precio: 650,
    piezas: 2,
    estado: "venta",
  },
  {
    nombre: "Legolas #628",
    serie: "El señor de los anillos, Lord of the Rings",
    ruta: raiz + "lordRings/legolas628.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
  {
    nombre: "Winged Kuriboh #1601",
    serie: "Yu-Gi-Oh, Yu Gi Oh",
    ruta: raiz + "yugioh/kuriboAlado1601.png",
    precio: 300,
    piezas: 1,
    estado: "venta",
  },
];

export default Lista;
